### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Love Kafka Test",
  "email": "sabrrakh@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-11-20",
  "registeredate": "2026-02-12"
}

###